name: Run make test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    name: Run make test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup asdf
        uses: ynab/asdf-action@v1.2
        with:
          version: 0.16.7

      - name: Setup Node version
        working-directory: mobile
        run: |
          asdf plugin add nodejs
          asdf install nodejs
          echo "node_version=$(asdf current nodejs | xargs | cut -d ' ' -f 6)" >> $GITHUB_ENV

      - name: Set nodejs as global exec
        run: |
          asdf set -u nodejs ${{ env.node_version }}

      - name: Install dependencies
        working-directory: mobile
        run: npm ci

      - name: Run make test
        working-directory: mobile
        run: make test
